version: '0.4.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
configuration: Release
platform: Any CPU
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/Castle.Facilities.QuartzIntegration/Castle.Facilities.Quartz.csproj  --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish ./src/Castle.Facilities.QuartzIntegration/Castle.Facilities.Quartz.csproj 
after_build:
  # For once the build has completed