version: '0.4.0.{build}'

image: Visual Studio 2017

branches:
  only:
  - master
  
configuration: Release

platform: Any CPU

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
  
install:
  # Install repo specific stuff here
  
build:
  project: ./src/CastleQuartzFacility.sln
  verbosity: minimal
  publish_nuget: true
 
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/CastleQuartzFacility.sln  --verbosity minimal