version: 0.4.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: dotnet restore
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal