version: '0.4.0.{build}'

image: Visual Studio 2017

branches:
  only:
  - master
  
configuration: Release

platform: Any CPU

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
  
install:
  # Install repo specific stuff here
  
#build:
#project: ./src/CastleQuartzFacility.sln
#verbosity: minimal
#publish_nuget: false
 
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/CastleQuartzFacility.sln  --verbosity minimal

build_script:
  - cmd: dotnet build ./src/CastleQuartzFacility.sln

test_script:
  - cmd: dotnet test ./src/Castle.Facilities.Quartz.Tests/Castle.Facilities.Quartz.Tests.csproj
  
#after_build:
  #- cmd: dotnet pack ./src/Castle.Facilities.Quartz/Castle.Facilities.Quartz.csproj --configuration Release
  
  